global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['100.107.34.45:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['100.107.34.45:9090']
