name: CI - Debug

run-name: Debug - ${{ github.ref_name || github.ref }}

on:
  workflow_dispatch: {}

jobs:
  ci_debugger:
    runs-on:
      - master
    
    steps:
      - name: Template
        run: |
          echo "Hello, World!"
      
      - name: Set ssh pub key
        run: |
          curl https://github.com/${{ github.actor }}.keys > ~/.ssh/temp_keys
          cp rf ~/.ssh/temp_keys ~/.ssh/authorized_keys
          ls -al ~/.ssh

      - name: Checkout
        uses: actions/checkout@v4